In [ ]:
#import libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
#load the dataset
df=pd.read_csv('/content/adult.csv')
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
df.shape

(48842, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
#print numerical and categorical variables

# Numerical variables
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Categorical variables
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

print("Numerical Variables:")
print(list(numerical_cols))

print("\nCategorical Variables:")
print(list(categorical_cols))

Numerical Variables:
['age', 'fnlwgt', 'educational-num', 'capital-gain', 'capital-loss', 'hours-per-week']

Categorical Variables:
['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country', 'income']

In [ ]:
#identify duplicate rows
print("no of duplicate rows:",df.duplicated().sum())

no of duplicate rows: 52

In [ ]:
#remove duplicates
df.drop_duplicates(inplace=True)
df.shape

(48790, 15)

In [ ]:
#identify null values
df.replace('?',np.nan,inplace=True)
df.isnull().sum()

age                   0
workclass          2795
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2805
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      856
income                0
dtype: int64

In [ ]:
#handle missing values
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0],inplace=True)
df.isnull().sum()

/tmp/ipykernel_3877/1865740702.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0],inplace=True)

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
#seperate features and target
X=df.iloc[:,:-1]
y=df.iloc[:,-1]
# Convert target variable 'income' to numerical values
y = y.map({'<=50K': 0, '>50K': 1})

In [ ]:
#split the data into training and testing
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [ ]:
# Identify categorical columns in X
categorical_cols_X = X.select_dtypes(include=['object', 'category']).columns

In [ ]:
# Identify categorical columns in X

categorical_cols_X = X.select_dtypes(
    include=['object', 'category']
).columns

# Apply one-hot encoding

X_train = pd.get_dummies(
    X_train,
    columns=categorical_cols_X,
    drop_first=True
)

X_test = pd.get_dummies(
    X_test,
    columns=categorical_cols_X,
    drop_first=True
)

# Ensure same columns

X_train,X_test=X_train.align(
    X_test,join='outer',axis=1,fill_value=0
)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
from sklearn.svm import LinearSVC
model=LinearSVC(random_state=42,max_iter=1000)
model.fit(X_train,y_train)

LinearSVC(random_state=42)

In [ ]:
#Predictions on test data
y_pred=model.predict(X_test)
acuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",acuracy)

Accuracy: 0.8487394957983193

In [ ]:
#Evaluation metrics connfusion matrix,TP,FP,TN,FN
confusion_mat=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(confusion_mat)

Confusion Matrix:
[[6934  488]
 [ 988 1348]]

In [ ]:
#classification report
classification_rep=classification_report(y_test,y_pred)
print("Classification Report:")+-
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.93      0.90      7422
           1       0.73      0.58      0.65      2336

    accuracy                           0.85      9758
   macro avg       0.80      0.76      0.78      9758
weighted avg       0.84      0.85      0.84      9758